### ISSUE TITLE
1.37版本http-want-digest选项警告

### ISSUE THREAD

**Issue by auqhjjqdo** [myfreeer/aria2-build-msys2#17]
![image](https://github.com/myfreeer/aria2-build-msys2/assets/84632728/9f6286de-19a5-46e8-ad1a-6fcd7fce9aa3)
1.37版本在`aria2.conf`配置文件中添加`http-want-digest=false`会提示如图的警告，之前的版本没有出现

**Comment by myfreeer** [comment]
@zhengqwe Thanks for this info, should be fixed by https://github.com/myfreeer/aria2-build-msys2/commit/a72a35802a173c06a26399d62c481af63f09e140
感谢提供信息，已在  https://github.com/myfreeer/aria2-build-msys2/commit/a72a35802a173c06a26399d62c481af63f09e140 中修复。
Releases in this repo are compiled on appveyor ci, for example [this](https://ci.appveyor.com/project/myfreeer/aria2-build-msys2/builds/48692719)
本库的发布通过appveyor ci编译，比如[这个](https://ci.appveyor.com/project/myfreeer/aria2-build-msys2/builds/48692719)
